name: Run tests

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest behave
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Create secret file
      env: # Set the secret as an input
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: |
        echo "{\"token\": \"$BOT_TOKEN\"}" > Src/Configs/secrets.json
    - name: Unit tests with unittest
      run: |
        cd Test/UnitTest
        python -m pytest
      env:
        PYTHONPATH: /home/runner/work/Scrimbot-2.0/Scrimbot-2.0/Src/
    - name: Acceptance tests with behave
      run: |
        behave --junit
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: reports/*.xml