name: Run tests

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest behave
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Create files
      env: # Set the secret as an input
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: |
        mkdir DataFiles
        echo "{\"token\": \"$BOT_TOKEN\"}" > Src/Configs/secrets.json
        
    - name: Acceptance tests with behave
      run: |
        behave Test/AcceptanceTest --junit
      env:
        PYTHONPATH: /home/runner/work/Scrimbot-2.0/Scrimbot-2.0/Src/
        
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()    # run this step even if previous step failed
      with:
        name: Behave test results
        path: reports/*.xml
        reporter: java-junit
        fail-on-error: 'false'
      id: create_report
   
    - name: Discord Embed
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.WEBHOOK_URL }}
        title: "test run"
        description: "✅ Passed: ${{steps.create_report.outputs.passed}}\n⛔ Failed: ${{steps.create_report.outputs.failed}}\n⌛ Skipped: ${{steps.create_report.outputs.skipped}}\n⏱ Running time: ${{steps.create_report.outputs.time}}"
        color: 0x474747
        username: GitHub Actions
        avatar_url: "https://cdn3.iconfinder.com/data/icons/inficons/512/github.png"
